-- | Emit compiles (already normalized) Join IR to Zig source text.
--
-- Every compiled unit — a top-level definition, a lifted @Lambda@ body, a
-- lifted (escaping) join consumer, a lifted @Object@ field, or a lifted
-- @Cocase@ branch — becomes an independent Zig function with the uniform
-- signature @fn (cap: []const rt.Value, args: []const rt.Value) rt.Value@.
-- Captures and parameters are bound to ordinary @const@s at function entry;
-- the function body ends with exactly one @return@ per control-flow path.
--
-- A @Join name consumer stmt@ binding is either:
--
--   * 'Malgo.Backend.Zig.ClosureConv.Local' — never lifted. No Zig code is
--     emitted for the binding itself; instead @consumer@'s AST is recorded
--     in the (plain, explicitly threaded) local environment, and every
--     @Cut@\/@Primitive@ site that targets @name@ inlines @consumer@'s logic
--     applied to the computed value, in place. This is always sound because
--     'Malgo.Backend.Zig.ClosureConv.escapingNamesStatement' guarantees such
--     uses never leave the current function.
--   * 'Malgo.Backend.Zig.ClosureConv.Escaping' — lifted into its own
--     function (capturing its free variables), allocated once as a real
--     @rt.Closure@ Value bound to an ordinary Zig @const@, and invoked
--     through @rt.applyCovalue@ wherever it is used.
module Malgo.Backend.Zig.Emit (compileToZig, mangleId) where

import Data.Map.Strict qualified as Map
import Data.Set qualified as Set
import Data.Text qualified as T
import Data.Traversable (for)
import Effectful
import Effectful.Reader.Static (Reader, ask)
import Effectful.State.Static.Local (State)
import Malgo.Backend.Zig.ClosureConv
import Malgo.Backend.Zig.Normalize (normalizeStatement)
import Malgo.Backend.Zig.Runtime (zigRuntime)
import Malgo.Id
import Malgo.Module (ModuleName)
import Malgo.Prelude
import Malgo.Sequent.Core.Join
import Malgo.Sequent.Fun (Literal (..), Name, Pattern (..), Tag (..))

-- | Local (same-function) substitution environment: a join name classified
-- 'Local' maps to the 'Consumer' it was bound to, to be inlined at use.
type LocalEnv = Map Name Consumer

-- | Accumulated Zig function definitions produced by lifting, plus the
-- text of "the current position". Threaded explicitly (not via a Writer
-- effect) to keep the traversal simple; concatenation order does not
-- matter since Zig struct members may be declared in any order.
type Lifted = [Text]

compileToZig :: (State Uniq :> es, Reader ModuleName :> es) => Program -> Eff es Text
compileToZig program = do
  modName <- ask @ModuleName
  -- A module reachable via more than one import path (a diamond, e.g. a
  -- test case importing both Builtin and Prelude, which itself imports
  -- Builtin) appears once per path in the linked 'Program.definitions'.
  -- Scheme's `define` silently allows redefinition, but Zig errors on a
  -- duplicate struct member name, so definitions here are deduplicated by
  -- 'Malgo.Id.Id' (stable across import paths for the same 'External' def).
  let definitions = nubByName program.definitions
  (defsText, lifted1) <- foldDefs definitions
  entryStmt <- mainEntryStatement (findMain definitions)
  (entryText, lifted2) <- emitStatement Map.empty (classifyJoins entryStmt) entryStmt
  pure
    $ T.unlines
      [ "// Generated by the Malgo Zig backend from module " <> convertString (show modName) <> ".",
        "// Arena allocator only (Perceus RC lands in a later milestone): rt.dup/rt.drop",
        "// are not yet emitted; nothing is freed until process exit.",
        "const rt = struct {",
        zigRuntime,
        "};",
        "",
        T.intercalate "\n\n" (lifted1 <> lifted2),
        "",
        T.intercalate "\n\n" defsText,
        "",
        "fn zigMain(cap: []const rt.Value, args: []const rt.Value) rt.Value {",
        "_ = cap;\n_ = args;\n",
        entryText,
        "}",
        "",
        "pub fn main() void {",
        "    var arena = rt.newArena();",
        "    rt.g_arena = &arena;",
        "    _ = zigMain(&[_]rt.Value{}, &[_]rt.Value{});",
        "    rt.flushStdout();",
        "}"
      ]
  where
    foldDefs [] = pure ([], [])
    foldDefs ((_, name, retName, rawStmt) : rest) = do
      -- Normalize once per top-level definition: 'normalizeStatement'
      -- recurses into every nested Lambda/Object field/Cocase branch body,
      -- so this single call covers the whole tree reachable from here.
      let stmt = normalizeStatement rawStmt
      (bodyText, lifted) <- emitStatement Map.empty (classifyJoins stmt) stmt
      let def =
            "fn "
              <> mangleId name
              <> "(cap: []const rt.Value, args: []const rt.Value) rt.Value {\n"
              <> "_ = cap;\n" -- top-level defs never have captures.
              <> "const "
              <> mangleId retName
              <> " = args[0];\n"
              <> bodyText
              <> "\n}"
      (restText, restLifted) <- foldDefs rest
      pure (def : restText, lifted <> restLifted)

-- | Keep only the first definition for each 'Malgo.Id.Id', dropping later
-- occurrences reached via a different import path to the same module.
nubByName :: [(Range, Name, Name, Statement)] -> [(Range, Name, Name, Statement)]
nubByName = go Set.empty
  where
    go _ [] = []
    go seen (d@(_, name, _, _) : rest)
      | name `Set.member` seen = go seen rest
      | otherwise = d : go (Set.insert name seen) rest

-- | Find the definition named @main@, matching the interpreter's bootstrap
-- ('Malgo.Sequent.Eval.evalProgram'): the first definition (from any linked
-- module) whose 'Malgo.Id.Id.name' is exactly @"main"@.
findMain :: [(Range, Name, Name, Statement)] -> (Range, Name)
findMain defs = case [(range, name) | (range, name, _, _) <- defs, name.name == "main"] of
  (found : _) -> found
  [] -> error "Malgo.Backend.Zig.Emit: no top-level definition named `main`"

-- | Build the program's entry-point statement, mirroring
-- 'Malgo.Sequent.Eval.evalProgram'\'s bootstrap exactly: locate @main@,
-- then run @Invoke main afterMain@ where @afterMain@, once handed @main@'s
-- own value (a closure, by the @main : () -> a@ convention), applies it to
-- unit and a fresh @Finish@ continuation. Reusing 'Invoke' (rather than
-- inlining @main@'s body here) calls the same compiled function emitted by
-- 'compileToZig'\'s @foldDefs@, so @main@'s code is not duplicated.
mainEntryStatement :: (State Uniq :> es, Reader ModuleName :> es) => (Range, Name) -> Eff es Statement
mainEntryStatement (range, mainName) = do
  finishName <- newTemporalId "finish"
  afterMain <- newTemporalId "after_main"
  pure
    $ Join range finishName (Finish range)
    $ Join range afterMain (Apply range [Construct range Tuple [] []] [finishName])
    $ Invoke range mainName afterMain

emitStatement :: (State Uniq :> es, Reader ModuleName :> es) => LocalEnv -> Map Name Ownership -> Statement -> Eff es (Text, Lifted)
emitStatement env ownership = go
  where
    go (Cut producer k) = do
      (valueExpr, producerStmts, lifted1) <- emitProducer env ownership producer
      case Map.lookup k env of
        Just consumer -> do
          (bodyText, lifted2) <- emitConsumerApplication env ownership consumer valueExpr
          pure (producerStmts <> bodyText, lifted1 <> lifted2)
        Nothing -> pure (producerStmts <> "return rt.applyCovalue(" <> mangleId k <> ", " <> valueExpr <> ");\n", lifted1)
    go (Join _ name consumer stmt) = case Map.findWithDefault Local name ownership of
      Local -> emitStatement (Map.insert name consumer env) ownership stmt
      Escaping -> do
        (allocText, liftedFns) <- liftConsumer env ownership name consumer
        (restText, restLifted) <- emitStatement env ownership stmt
        pure (allocText <> restText, liftedFns <> restLifted)
    go (Primitive _ name producers k) = do
      (argExprs, producerStmts, lifted1) <- emitProducers env ownership producers
      let resultExpr = "rt." <> name <> "(&[_]rt.Value{" <> T.intercalate ", " argExprs <> "})"
      case Map.lookup k env of
        Just consumer -> do
          (bodyText, lifted2) <- emitConsumerApplicationViaTemp env ownership consumer resultExpr
          pure (producerStmts <> bodyText, lifted1 <> lifted2)
        Nothing -> pure (producerStmts <> "return rt.applyCovalue(" <> mangleId k <> ", " <> resultExpr <> ");\n", lifted1)
    go (Invoke _ name k) =
      pure ("return " <> mangleId name <> "(&[_]rt.Value{}, &[_]rt.Value{" <> mangleId k <> "});\n", [])
    go (ExternalCall range name producers k) = go (Primitive range name producers k)
    go (BinOp _ op lhs rhs k) = do
      (lhsExpr, lhsStmts, lifted1) <- emitProducer env ownership lhs
      (rhsExpr, rhsStmts, lifted2) <- emitProducer env ownership rhs
      let resultExpr = "rt." <> op <> "(&[_]rt.Value{" <> lhsExpr <> ", " <> rhsExpr <> "})"
      pure (lhsStmts <> rhsStmts <> "return rt.applyCovalue(" <> mangleId k <> ", " <> resultExpr <> ");\n", lifted1 <> lifted2)
    go (Ifz _ cond t e) = do
      (condExpr, condStmts, lifted1) <- emitProducer env ownership cond
      (thenText, lifted2) <- emitStatement env ownership t
      (elseText, lifted3) <- emitStatement env ownership e
      pure
        ( condStmts
            <> "if (rt.isZero("
            <> condExpr
            <> ")) {\n"
            <> thenText
            <> "} else {\n"
            <> elseText
            <> "}\n",
          lifted1 <> lifted2 <> lifted3
        )

-- | Apply an already-inlined 'Consumer' (from a 'Local' join) to a value
-- expression that is *not yet* bound to a Zig variable — used right after a
-- 'Primitive' call, where we want to avoid evaluating the primitive twice
-- if the consumer needs the value more than once (e.g. as multiple pattern
-- scrutinee accesses).
emitConsumerApplicationViaTemp :: (State Uniq :> es, Reader ModuleName :> es) => LocalEnv -> Map Name Ownership -> Consumer -> Text -> Eff es (Text, Lifted)
emitConsumerApplicationViaTemp env ownership consumer valueExpr = do
  tmp <- newTemporalId "prim_result"
  (bodyText, lifted) <- emitConsumerApplication env ownership consumer (mangleId tmp)
  pure ("const " <> mangleId tmp <> " = " <> valueExpr <> ";\n" <> bodyText, lifted)

-- | Apply a 'Consumer' to an already-available value expression, inline, in
-- the current function scope.
emitConsumerApplication :: (State Uniq :> es, Reader ModuleName :> es) => LocalEnv -> Map Name Ownership -> Consumer -> Text -> Eff es (Text, Lifted)
emitConsumerApplication env ownership consumer valueExpr = case consumer of
  Label _ name -> pure ("return rt.applyCovalue(" <> mangleId name <> ", " <> valueExpr <> ");\n", [])
  Apply _ producers returns -> do
    (argExprs, producerStmts, lifted) <- emitProducers env ownership producers
    let allArgs = argExprs <> map mangleId returns
    pure (producerStmts <> "return rt.callClosure(" <> valueExpr <> ", &[_]rt.Value{" <> T.intercalate ", " allArgs <> "});\n", lifted)
  Project _ field k ->
    pure ("return rt.projectField(" <> valueExpr <> ", " <> zigStringLit field <> ", " <> mangleId k <> ");\n", [])
  Then _ name stmt -> do
    (bodyText, lifted) <- emitStatement env ownership stmt
    -- `let _ = sideEffectingExpr; rest` (a discarded value, e.g. the `()`
    -- result of a statement run only for effect) binds a name never used
    -- in `rest`; Zig errors on an unused local just as on a pointless
    -- discard of a used one, so which to emit depends on `stmt`'s free vars.
    let discard = if name `Set.member` freeVarsStatement stmt then "" else "_ = " <> mangleId name <> ";\n"
    pure ("{\nconst " <> mangleId name <> " = " <> valueExpr <> ";\n" <> discard <> bodyText <> "}\n", lifted)
  Finish _ -> pure ("return " <> valueExpr <> ";\n", [])
  Select _ branches -> emitSelect env ownership valueExpr branches
  Destructor _ name producers k -> do
    (argExprs, producerStmts, lifted) <- emitProducers env ownership producers
    let allArgs = argExprs <> [mangleId k]
    pure (producerStmts <> "return rt.applyDestructor(" <> valueExpr <> ", " <> zigStringLit name <> ", &[_]rt.Value{" <> T.intercalate ", " allArgs <> "});\n", lifted)

emitSelect :: (State Uniq :> es, Reader ModuleName :> es) => LocalEnv -> Map Name Ownership -> Text -> [Branch] -> Eff es (Text, Lifted)
emitSelect env ownership scrutineeExpr branches = do
  tmp <- newTemporalId "scrutinee"
  let scrutVar = mangleId tmp
  (armsText, lifted) <- goBranches scrutVar branches
  pure ("{\nconst " <> scrutVar <> " = " <> scrutineeExpr <> ";\n" <> armsText <> "unreachable; // rt.panic(\"no matching branch\") above always diverges\n}\n", lifted)
  where
    goBranches _ [] = pure ("rt.panic(\"no matching branch\");\n", [])
    goBranches scrutVar (Branch _ pat stmt : rest) = do
      -- Zig errors on both an unused local `const` and a "pointless"
      -- `_ = x;` discard of a used one, so every pattern-bound name must be
      -- discarded if and only if the branch body never references it.
      let used = freeVarsStatement stmt
      (guardExpr, bindStmts) <- compilePattern used scrutVar pat
      (bodyText, lifted1) <- emitStatement env ownership stmt
      (restText, lifted2) <- goBranches scrutVar rest
      pure
        ( "if ("
            <> guardExpr
            <> ") {\n"
            <> bindStmts
            <> bodyText
            <> "} else {\n"
            <> restText
            <> "}\n",
          lifted1 <> lifted2
        )

-- | Compile a pattern match against a scrutinee Zig expression (a `const`
-- binding, safe to reference repeatedly) into a boolean guard expression and
-- the `const` declarations for pattern variables to splice before the branch
-- body. Mirrors 'Malgo.Sequent.Eval.match'/'matchDL'.
--
-- @used@ is the set of names free in the branch body: a pattern-bound name
-- outside it (e.g. a wildcard-style @_@ binder never referenced afterwards)
-- must be immediately discarded, since Zig errors on unused locals just as
-- it errors on discarding a name that *is* used elsewhere.
--
-- The renamer assigns wildcard (@_@) patterns a shared 'Malgo.Id.Id', so a
-- single pattern like @Nil _ -> ...@ matching multiple positions can bind
-- the *same* name more than once — harmless for the evaluator's Map-based
-- environment (last write wins), but Zig rejects redeclaring a @const@ in
-- one scope. A locally-threaded "seen" set (scoped to one top-level
-- 'compilePattern' call, i.e. one branch's pattern) drops every
-- redeclaration after the first.
--
-- Monadic (needs fresh names): unlike a struct's @Destruct@ fields, which
-- are plain, side-effect-free field accesses safe to re-evaluate, an
-- @Object@ record's fields are call-by-name and may have effects
-- ('Malgo.Sequent.Eval.evalConsumer'\'s @Project@ case re-runs the field's
-- statement on every force) — an @Expand@ sub-pattern must therefore force
-- each field into a fresh @const@ exactly once, not inline the force
-- expression everywhere it is used.
--
-- A pattern field absent from the record (the evaluator's
-- @Map.intersectionWith@ silently treats this as still matching) is not
-- implemented: it panics at runtime instead. Real Malgo programs pattern
-- match only on fields a record's row guarantees are present, so this
-- edge case is not expected to be exercised.
compilePattern :: (State Uniq :> es, Reader ModuleName :> es) => Set Name -> Text -> Pattern -> Eff es (Text, Text)
compilePattern used scrutinee pat = do
  (guard, binds, _) <- go Set.empty scrutinee pat
  pure (guard, binds)
  where
    go :: (State Uniq :> es, Reader ModuleName :> es) => Set Name -> Text -> Pattern -> Eff es (Text, Text, Set Name)
    go seen s (PVar _ name)
      | name `Set.member` seen = pure ("true", "", seen)
      | otherwise =
          let discard = if name `Set.member` used then "" else "_ = " <> mangleId name <> ";\n"
           in pure ("true", "const " <> mangleId name <> " = " <> s <> ";\n" <> discard, Set.insert name seen)
    go seen s (PLiteral _ lit) = pure (literalEqExpr s lit, "", seen)
    go seen s (Destruct _ tag pats) = do
      let tagCheck = s <> ".kind == .strukt and rt.tagEq(" <> s <> ".payload.strukt.tag, " <> compileTag tag <> ")"
      (subs, seen') <- goFields seen (zip [0 :: Int ..] pats)
      let guards = tagCheck : [g | (g, _) <- subs, g /= "true"]
          binds = T.concat [b | (_, b) <- subs]
      pure (T.intercalate " and " guards, binds, seen')
      where
        goFields seen0 [] = pure ([], seen0)
        goFields seen0 ((i, p) : rest) = do
          (g, b, seen1) <- go seen0 (s <> ".payload.strukt.fields[" <> convertString (show i) <> "]") p
          (restResults, seen2) <- goFields seen1 rest
          pure ((g, b) : restResults, seen2)
    go seen s (Expand _ fieldPats) = do
      -- Fields forced in ascending name order (Map.toList), matching
      -- Eval.hs's matchExpand.
      (subs, seen') <- goFields seen (Map.toList fieldPats)
      let guards = (s <> ".kind == .record") : [g | (g, _) <- subs, g /= "true"]
          binds = T.concat [b | (_, b) <- subs]
      pure (T.intercalate " and " guards, binds, seen')
      where
        goFields seen0 [] = pure ([], seen0)
        goFields seen0 ((fieldName, p) : rest) = do
          forced <- newTemporalId "expand"
          let forceStmt =
                "const "
                  <> mangleId forced
                  <> " = rt.forceField("
                  <> s
                  <> ", "
                  <> zigStringLit fieldName
                  <> ") orelse rt.panic(\"Expand: missing field "
                  <> fieldName
                  <> "\");\n"
          (g, b, seen1) <- go seen0 (mangleId forced) p
          (restResults, seen2) <- goFields seen1 rest
          pure ((g, forceStmt <> b) : restResults, seen2)

literalEqExpr :: Text -> Literal -> Text
literalEqExpr scrutinee = \case
  Int32 n -> scrutinee <> ".kind == .int32 and " <> scrutinee <> ".payload.int32 == " <> convertString (show n)
  Int64 n -> scrutinee <> ".kind == .int64 and " <> scrutinee <> ".payload.int64 == " <> convertString (show n)
  Float f -> scrutinee <> ".kind == .float and " <> scrutinee <> ".payload.float == " <> convertString (show f)
  Double d -> scrutinee <> ".kind == .double and " <> scrutinee <> ".payload.double == " <> convertString (show d)
  Char c -> scrutinee <> ".kind == .char and " <> scrutinee <> ".payload.char == " <> convertString (show (fromEnum c)) <> ""
  String s -> scrutinee <> ".kind == .string and rt.stringEq(" <> scrutinee <> ".payload.string, " <> zigStringLit s <> ")"

compileTag :: Tag -> Text
compileTag Tuple = "rt.Tag{ .tuple = {} }"
compileTag (Tag t) = "rt.Tag{ .named = " <> zigStringLit t <> " }"

-- | Lift an 'Escaping' join's consumer into its own top-level Zig function,
-- returning the allocation statement to bind @name@ and the function
-- definition to append to the program.
liftConsumer :: (State Uniq :> es, Reader ModuleName :> es) => LocalEnv -> Map Name Ownership -> Name -> Consumer -> Eff es (Text, Lifted)
liftConsumer _outerEnv _outerOwnership name consumer = do
  fnId <- newTemporalId "join"
  let captures = Set.toList (freeVarsConsumer consumer)
      captureBinds = T.concat [bindCapture i c | (i, c) <- zip [0 :: Int ..] captures]
      -- `args[0]` (the value handed to this consumer) is always referenced
      -- by 'emitConsumerApplication' below; `cap` is unused exactly when
      -- there are no captures.
      discardCap = if null captures then "_ = cap;\n" else ""
  (bodyText, lifted) <- emitConsumerApplication Map.empty (classifyJoinsConsumer consumer) consumer "args[0]"
  let fnText =
        "fn "
          <> mangleId fnId
          <> "(cap: []const rt.Value, args: []const rt.Value) rt.Value {\n"
          <> discardCap
          <> captureBinds
          <> bodyText
          <> "\n}"
      allocText =
        "const "
          <> mangleId name
          <> " = rt.mkClosure(&"
          <> mangleId fnId
          <> ", &[_]rt.Value{"
          <> T.intercalate ", " (map mangleId captures)
          <> "});\n"
  pure (allocText, fnText : lifted)
  where
    bindCapture i c = "const " <> mangleId c <> " = cap[" <> convertString (show i) <> "];\n"

emitProducers :: (State Uniq :> es, Reader ModuleName :> es) => LocalEnv -> Map Name Ownership -> [Producer] -> Eff es ([Text], Text, Lifted)
emitProducers _ _ [] = pure ([], "", [])
emitProducers env ownership (p : ps) = do
  (expr, stmts, lifted1) <- emitProducer env ownership p
  (exprs, restStmts, lifted2) <- emitProducers env ownership ps
  pure (expr : exprs, stmts <> restStmts, lifted1 <> lifted2)

emitProducer :: (State Uniq :> es, Reader ModuleName :> es) => LocalEnv -> Map Name Ownership -> Producer -> Eff es (Text, Text, Lifted)
emitProducer _ _ (Var _ name) = pure (mangleId name, "", [])
emitProducer _ _ (Literal _ lit) = pure (compileLiteral lit, "", [])
emitProducer env ownership (Construct _ tag producers returns) = do
  (argExprs, stmts, lifted) <- emitProducers env ownership producers
  let allFields = argExprs <> map mangleId returns
  pure ("rt.mkStruct(" <> compileTag tag <> ", &[_]rt.Value{" <> T.intercalate ", " allFields <> "})", stmts, lifted)
emitProducer _outerEnv _outerOwnership (Lambda _ params stmt) = do
  fnId <- newTemporalId "lambda"
  let captures = Set.toList (freeVarsStatement stmt Set.\\ Set.fromList params)
      captureBinds = T.concat [bindCapture i c | (i, c) <- zip [0 :: Int ..] captures]
      used = freeVarsStatement stmt
      paramBinds = bindParams used Set.empty (zip [0 :: Int ..] params)
      -- `params` always contains at least the return continuation (ToCore
      -- appends it to every surface lambda), so `args` is always used.
      discardCap = if null captures then "_ = cap;\n" else ""
  (bodyText, lifted) <- emitStatement Map.empty (classifyJoins stmt) stmt
  let fnText =
        "fn "
          <> mangleId fnId
          <> "(cap: []const rt.Value, args: []const rt.Value) rt.Value {\n"
          <> discardCap
          <> captureBinds
          <> paramBinds
          <> bodyText
          <> "\n}"
      allocExpr = "rt.mkClosure(&" <> mangleId fnId <> ", &[_]rt.Value{" <> T.intercalate ", " (map mangleId captures) <> "})"
  pure (allocExpr, "", fnText : lifted)
  where
    bindCapture i c = "const " <> mangleId c <> " = cap[" <> convertString (show i) <> "];\n"
    -- The renamer can assign the same wildcard 'Malgo.Id.Id' to more than
    -- one surface parameter (e.g. two `_`s), which Zig would see as
    -- redeclaring a `const`; skip a name already bound earlier in this
    -- same parameter list, and discard any binding the body never uses.
    bindParams _ _ [] = ""
    bindParams used seen ((i, p) : rest)
      | p `Set.member` seen = bindParams used seen rest
      | otherwise =
          let discard = if p `Set.member` used then "" else "_ = " <> mangleId p <> ";\n"
           in "const " <> mangleId p <> " = args[" <> convertString (show i) <> "];\n" <> discard <> bindParams used (Set.insert p seen) rest
emitProducer _outerEnv _outerOwnership (Object _ fields) = do
  -- A record's fields share ONE captured environment (mirrors the
  -- evaluator's `Record env fields`, Eval.hs) — the *allocation*'s capture
  -- list is the union of every field's own free variables (excluding that
  -- field's own return name). But each individual field function only
  -- references a subset of that shared list, so (unlike a Lambda, where
  -- captures are computed per-function) binding *every* shared capture
  -- unconditionally in *every* field's function body would leave some
  -- unused in fields that do not reference them — Zig rejects that. Each
  -- field's own bindings are therefore discarded per-field based on that
  -- field's own free variables, not the shared union.
  let sharedCaptures = Set.toList (Set.unions [freeVarsStatement stmt Set.\\ Set.singleton ret | (ret, stmt) <- Map.elems fields])
      discardCap = if null sharedCaptures then "_ = cap;\n" else ""
  fieldFns <- for (Map.toList fields) \(fieldName, (retName, stmt)) -> do
    fnId <- newTemporalId "field"
    let usedByThisField = freeVarsStatement stmt Set.\\ Set.singleton retName
        captureBinds = T.concat [bindCapture usedByThisField i c | (i, c) <- zip [0 :: Int ..] sharedCaptures]
    (bodyText, lifted) <- emitStatement Map.empty (classifyJoins stmt) stmt
    let fnText =
          "fn "
            <> mangleId fnId
            <> "(cap: []const rt.Value, args: []const rt.Value) rt.Value {\n"
            <> discardCap
            <> captureBinds
            <> "const "
            <> mangleId retName
            <> " = args[0];\n"
            <> bodyText
            <> "\n}"
    pure (fieldName, fnId, fnText, lifted)
  let fieldEntries = T.intercalate ", " [".{ .name = " <> zigStringLit fieldName <> ", .code = &" <> mangleId fnId <> " }" | (fieldName, fnId, _, _) <- fieldFns]
      allocExpr =
        "rt.mkRecord(&[_]rt.NamedField{"
          <> fieldEntries
          <> "}, &[_]rt.Value{"
          <> T.intercalate ", " (map mangleId sharedCaptures)
          <> "})"
      allLifted = concatMap (\(_, _, fnText, lifted) -> fnText : lifted) fieldFns
  pure (allocExpr, "", allLifted)
  where
    bindCapture usedByThisField i c =
      "const " <> mangleId c <> " = cap[" <> convertString (show i) <> "];\n" <> if c `Set.member` usedByThisField then "" else "_ = " <> mangleId c <> ";\n"
emitProducer _ _ (Mu _ _ _) =
  error "Malgo.Backend.Zig.Emit: Mu in producer position should have been eliminated by Normalize"
emitProducer _ _ (Cocase _ branches) =
  let vars = Set.toList (Set.unions [freeVarsStatement stmt Set.\\ Set.fromList bound | (_, bound, stmt) <- branches])
   in pure ("rt.panicUnimplemented(\"Cocase\")", discardFreeVars vars, [])

-- | Read a set of names into a discarded array-literal expression: this
-- counts as *using* each one (Zig reads them to build the array) without
-- individually discarding any of them, so it never conflicts with a
-- genuine use of the same name elsewhere in scope.
discardFreeVars :: [Name] -> Text
discardFreeVars [] = ""
discardFreeVars vars = "_ = [_]rt.Value{" <> T.intercalate ", " (map mangleId vars) <> "};\n"

compileLiteral :: Literal -> Text
compileLiteral (Int32 n) = "rt.mkInt32(" <> convertString (show n) <> ")"
compileLiteral (Int64 n) = "rt.mkInt64(" <> convertString (show n) <> ")"
compileLiteral (Float f) = "rt.mkFloat(" <> convertString (show f) <> ")"
compileLiteral (Double d) = "rt.mkDouble(" <> convertString (show d) <> ")"
compileLiteral (Char c) = "rt.mkChar(" <> convertString (show (fromEnum c)) <> ")"
compileLiteral (String s) = "rt.mkString(" <> zigStringLit s <> ")"

-- | Zig string literal, escaped. Non-ASCII bytes pass through raw (Zig
-- source is UTF-8 and accepts literal UTF-8 in string literals).
zigStringLit :: Text -> Text
zigStringLit t = "\"" <> T.concatMap escapeChar t <> "\""
  where
    escapeChar '\\' = "\\\\"
    escapeChar '"' = "\\\""
    escapeChar '\n' = "\\n"
    escapeChar '\r' = "\\r"
    escapeChar '\t' = "\\t"
    escapeChar '\0' = "\\x00"
    escapeChar c
      | fromEnum c < 0x20 = "\\x" <> T.justifyRight 2 '0' (convertString (showHex (fromEnum c)))
      | otherwise = T.singleton c
    showHex n = go n ""
      where
        digits = "0123456789abcdef"
        go 0 acc = if null acc then "0" else acc
        go x acc = go (x `div` 16) (digits !! (x `mod` 16) : acc)

-- | Mangle a Malgo 'Id' into a Zig identifier using Zig's raw-identifier
-- syntax (@\@\"...\"@), which accepts almost any string. This sidesteps
-- Zig keyword collisions entirely (@\@\"error\"@, @\@\"fn\"@, @\@\"test\"@,
-- ... are all valid) without a bespoke substitution table, and reuses
-- 'Malgo.Id.idToText' for a globally-unique canonical name.
mangleId :: Id -> Text
mangleId ident = "@\"" <> T.concatMap escapeChar (idToText ident) <> "\""
  where
    escapeChar '\\' = "\\\\"
    escapeChar '"' = "\\\""
    escapeChar c = T.singleton c
