-- | Emit prints the backend 'Ir.Program' (produced by
-- 'Malgo.Backend.Zig.ClosureConv.convertProgram') as Zig source text.
--
-- Every 'Ir.Func' becomes a Zig function with the uniform self-passing
-- signature @fn (self: rt.Value, args: []const rt.Value) rt.Value@: a
-- closure\/record field receives the closure object itself as @self@ and
-- reads its captures out of it ('Ir.ReadCapture' → @rt.capturesOf(self)@),
-- while a top-level definition is called directly with the @rt.no_self@
-- sentinel and ignores it. Self-passing is what makes Perceus's
-- "a call consumes one reference of the callee" rule implementable: the
-- callee dups the captures it needs before (in a later milestone) dropping
-- @self@ — the caller has no post-call point to do either, since every
-- call is a tail call.
--
-- Zig errors on both an unused local @const@ and a pointless @_ = x;@
-- discard of a used one, so the printer discards exactly the bindings
-- (and @self@\/@args@) that the rest of the function never references.
module Malgo.Backend.Zig.Emit (emitProgram, mangleId) where

import Data.Set qualified as Set
import Data.Text qualified as T
import Effectful
import Effectful.Reader.Static (Reader, ask)
import Malgo.Backend.Zig.Ir qualified as Ir
import Malgo.Backend.Zig.Runtime (zigRuntime)
import Malgo.Id
import Malgo.Module (ModuleName)
import Malgo.Prelude
import Malgo.Sequent.Fun (Literal (..), Name, Tag (..))

emitProgram :: (Reader ModuleName :> es) => Ir.Program -> Eff es Text
emitProgram program = do
  modName <- ask @ModuleName
  let entryCall = case program.entry of
        Nothing -> ""
        -- The Finish value propagates up the tail-call chain to here;
        -- dropping it is the last consumption the leak check relies on.
        Just name -> "    rt.drop(" <> mangleId name <> "(rt.no_self, &[_]rt.Value{}));"
  pure
    $ T.unlines
      [ "// Generated by the Malgo Zig backend from module " <> convertString (show modName) <> ".",
        "// Memory: Perceus reference counting (dup/drop inserted by the compiler);",
        "// a leaked Value at exit prints MALGO-LEAK to stderr and exits with 83.",
        "const rt = struct {",
        zigRuntime,
        "};",
        "",
        T.intercalate "\n\n" (map emitFunc program.funcs),
        "",
        "pub fn main(rt_init: rt.std.process.Init.Minimal) void {",
        "    rt.setArgv(rt_init.args.vector);",
        "    rt.initHeap();",
        entryCall,
        "    rt.flushStdout();",
        "    rt.exitWithLeakCheck();",
        "}"
      ]

emitFunc :: Ir.Func -> Text
emitFunc fn =
  "fn "
    <> mangleId fn.name
    <> "(self: rt.Value, args: []const rt.Value) rt.Value {\n"
    <> discardSelf
    <> discardArgs
    <> paramBinds
    <> emitBlock pv fn.body
    <> "}"
  where
    pv n = if n == fn.selfVar then "self" else mangleId n
    bodyFree = Ir.freeVarsBlock fn.body
    discardSelf = if fn.selfVar `Set.member` bodyFree then "" else "_ = self;\n"
    discardArgs = if null fn.params then "_ = args;\n" else ""
    paramBinds =
      T.concat
        [ "const "
            <> pv p
            <> " = args["
            <> convertString (show i)
            <> "];\n"
            <> (if p `Set.member` bodyFree then "" else "_ = " <> pv p <> ";\n")
        | (i, p) <- zip [0 :: Int ..] fn.params
        ]

emitBlock :: (Name -> Text) -> Ir.Block -> Text
emitBlock pv (Ir.Block stmts0 terminator) = go stmts0
  where
    go [] = emitTerminator pv terminator
    -- 'Ir.PanicExpr' is noreturn: nothing after it in this block is
    -- reachable, and Zig rejects unreachable statements, so printing
    -- truncates here.
    go (Ir.Let _ (Ir.PanicExpr what) : _) = "rt.panicUnimplemented(" <> zigStringLit what <> ");\n"
    go (Ir.Let x e : rest) =
      let usedLater = x `Set.member` Ir.freeVarsBlock (Ir.Block rest terminator)
          discard = if usedLater then "" else "_ = " <> pv x <> ";\n"
       in "const " <> pv x <> " = " <> emitExpr pv e <> ";\n" <> discard <> go rest
    go (Ir.Dup x : rest) = "rt.dup(" <> pv x <> ");\n" <> go rest
    go (Ir.Drop x : rest) = "rt.drop(" <> pv x <> ");\n" <> go rest

emitTerminator :: (Name -> Text) -> Ir.Terminator -> Text
emitTerminator pv = \case
  Ir.TApplyCo k v -> "return rt.applyCovalue(" <> pv k <> ", " <> pv v <> ");\n"
  Ir.TCallClosure f args -> "return rt.callClosure(" <> pv f <> ", " <> valueSlice pv args <> ");\n"
  Ir.TStaticCall fn args -> "return " <> mangleId fn <> "(rt.no_self, " <> valueSlice pv args <> ");\n"
  Ir.TProject v field k -> "return rt.projectField(" <> pv v <> ", " <> zigStringLit field <> ", " <> pv k <> ");\n"
  Ir.TDestruct v name args -> "return rt.applyDestructor(" <> pv v <> ", " <> zigStringLit name <> ", " <> valueSlice pv args <> ");\n"
  Ir.TReturn v -> "return " <> pv v <> ";\n"
  Ir.TIf guard t e ->
    "if ("
      <> emitGuard pv guard
      <> ") {\n"
      <> emitBlock pv t
      <> "} else {\n"
      <> emitBlock pv e
      <> "}\n"
  Ir.TPanic msg -> "rt.panic(" <> zigStringLit msg <> ");\n"

emitGuard :: (Name -> Text) -> Ir.Guard -> Text
emitGuard pv = \case
  Ir.GAnd [] -> "true"
  Ir.GAnd tests -> T.intercalate " and " (map (emitTest pv) tests)
  Ir.GIsZero v -> "rt.isZero(" <> pv v <> ")"

emitTest :: (Name -> Text) -> Ir.Test -> Text
emitTest pv = \case
  Ir.TKindIs p kindName -> emitPath pv p <> ".kind == ." <> kindName
  Ir.TTagEq p tag ->
    let s = emitPath pv p
     in s <> ".kind == .strukt and rt.tagEq(" <> s <> ".payload.strukt.tag, " <> compileTag tag <> ")"
  Ir.TLitEq p lit -> literalEqExpr (emitPath pv p) lit

emitPath :: (Name -> Text) -> Ir.Path -> Text
emitPath pv (Ir.PRoot v) = pv v
emitPath pv (Ir.PField p i) = emitPath pv p <> ".payload.strukt.fields[" <> convertString (show i) <> "]"

emitExpr :: (Name -> Text) -> Ir.Expr -> Text
emitExpr pv = \case
  Ir.Lit lit -> compileLiteral lit
  Ir.MkStruct tag vs -> "rt.mkStruct(" <> compileTag tag <> ", " <> valueSlice pv vs <> ")"
  Ir.MkClosure fn vs -> "rt.mkClosure(&" <> mangleId fn <> ", " <> valueSlice pv vs <> ")"
  Ir.MkRecord fields vs ->
    "rt.mkRecord(&[_]rt.NamedField{"
      <> T.intercalate ", " [".{ .name = " <> zigStringLit fieldName <> ", .code = &" <> mangleId fn <> " }" | (fieldName, fn) <- fields]
      <> "}, "
      <> valueSlice pv vs
      <> ")"
  Ir.Prim name vs -> "rt." <> name <> "(" <> valueSlice pv vs <> ")"
  Ir.ReadPath p -> emitPath pv p
  Ir.ReadCapture self i -> "rt.capturesOf(" <> pv self <> ")[" <> convertString (show i) <> "]"
  Ir.Force v field ->
    "rt.forceField("
      <> pv v
      <> ", "
      <> zigStringLit field
      <> ") orelse rt.panic(\"Expand: missing field "
      <> field
      <> "\")"
  -- Handled (and truncated after) in 'emitBlock'.
  Ir.PanicExpr what -> "rt.panicUnimplemented(" <> zigStringLit what <> ")"

valueSlice :: (Name -> Text) -> [Name] -> Text
valueSlice pv vs = "&[_]rt.Value{" <> T.intercalate ", " (map pv vs) <> "}"

literalEqExpr :: Text -> Literal -> Text
literalEqExpr scrutinee = \case
  Int32 n -> scrutinee <> ".kind == .int32 and " <> scrutinee <> ".payload.int32 == " <> convertString (show n)
  Int64 n -> scrutinee <> ".kind == .int64 and " <> scrutinee <> ".payload.int64 == " <> convertString (show n)
  Float f -> scrutinee <> ".kind == .float and " <> scrutinee <> ".payload.float == " <> convertString (show f)
  Double d -> scrutinee <> ".kind == .double and " <> scrutinee <> ".payload.double == " <> convertString (show d)
  Char c -> scrutinee <> ".kind == .char and " <> scrutinee <> ".payload.char == " <> convertString (show (fromEnum c)) <> ""
  String s -> scrutinee <> ".kind == .string and rt.stringEq(" <> scrutinee <> ".payload.string, " <> zigStringLit s <> ")"

compileTag :: Tag -> Text
compileTag Tuple = "rt.Tag{ .tuple = {} }"
compileTag (Tag t) = "rt.Tag{ .named = " <> zigStringLit t <> " }"

compileLiteral :: Literal -> Text
compileLiteral (Int32 n) = "rt.mkInt32(" <> convertString (show n) <> ")"
compileLiteral (Int64 n) = "rt.mkInt64(" <> convertString (show n) <> ")"
compileLiteral (Float f) = "rt.mkFloat(" <> convertString (show f) <> ")"
compileLiteral (Double d) = "rt.mkDouble(" <> convertString (show d) <> ")"
compileLiteral (Char c) = "rt.mkChar(" <> convertString (show (fromEnum c)) <> ")"
compileLiteral (String s) = "rt.mkString(" <> zigStringLit s <> ")"

-- | Zig string literal, escaped. Non-ASCII bytes pass through raw (Zig
-- source is UTF-8 and accepts literal UTF-8 in string literals).
zigStringLit :: Text -> Text
zigStringLit t = "\"" <> T.concatMap escapeChar t <> "\""
  where
    escapeChar '\\' = "\\\\"
    escapeChar '"' = "\\\""
    escapeChar '\n' = "\\n"
    escapeChar '\r' = "\\r"
    escapeChar '\t' = "\\t"
    escapeChar '\0' = "\\x00"
    escapeChar c
      | fromEnum c < 0x20 = "\\x" <> T.justifyRight 2 '0' (convertString (showHex (fromEnum c)))
      | otherwise = T.singleton c
    showHex n = go n ""
      where
        digits = "0123456789abcdef"
        go 0 acc = if null acc then "0" else acc
        go x acc = go (x `div` 16) (digits !! (x `mod` 16) : acc)

-- | Mangle a Malgo 'Id' into a Zig identifier using Zig's raw-identifier
-- syntax (@\@\"...\"@), which accepts almost any string. This sidesteps
-- Zig keyword collisions entirely (@\@\"error\"@, @\@\"fn\"@, @\@\"test\"@,
-- ... are all valid) without a bespoke substitution table, and reuses
-- 'Malgo.Id.idToText' for a globally-unique canonical name.
mangleId :: Id -> Text
mangleId ident = "@\"" <> T.concatMap escapeChar (idToText ident) <> "\""
  where
    escapeChar '\\' = "\\\\"
    escapeChar '"' = "\\\""
    escapeChar c = T.singleton c
