#!/usr/bin/env bash
# Runtime benchmark: Haskell malgo vs. Lean malgo, per the M9 plan entry
# ("hyperfine Haskell-vs-Lean benchmark in bench/"). This is a RUNTIME
# comparison of the two `malgo` binaries themselves — unrelated to the
# other files already under bench/ (baseline-*.json, ghc-timing-baseline.log,
# etc.), which measure GHC's own BUILD time from an earlier, separate
# optimization effort.
#
# Usage:
#   HS_MALGO=<path> LEAN_MALGO=<path> bash bench/lean-vs-haskell.sh
#
# Defaults (if the env vars are unset): `cabal list-bin exe:malgo` for
# Haskell, `lean/.lake/build/bin/malgo` for Lean. Both must already be
# built (`cabal build exe:malgo`; `cd lean && lake build malgo`) — this
# script does not build them, to keep benchmark runs from being skewed by
# a cold build.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

if ! command -v hyperfine >/dev/null 2>&1; then
  echo "hyperfine not found on PATH (pinned in mise.toml: 'mise install hyperfine')." >&2
  exit 1
fi

HS_MALGO="${HS_MALGO:-$(cabal list-bin exe:malgo 2>/dev/null || true)}"
LEAN_MALGO="${LEAN_MALGO:-lean/.lake/build/bin/malgo}"

if [ -z "$HS_MALGO" ] || [ ! -x "$HS_MALGO" ]; then
  echo "Haskell malgo executable not found (set HS_MALGO, or run 'cabal build exe:malgo')." >&2
  exit 1
fi
if [ ! -x "$LEAN_MALGO" ]; then
  echo "Lean malgo executable not found at $LEAN_MALGO (set LEAN_MALGO, or run 'cd lean && lake build malgo')." >&2
  exit 1
fi

FIXTURE="bench/fixtures/BenchFib.mlg"
OUT_MD="bench/lean-vs-haskell.md"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "=== eval (small-step interpreter): naive fib(15), $FIXTURE ==="
hyperfine \
  --warmup 1 \
  --export-markdown "$WORK/eval.md" \
  -n "Haskell (eval)" "$HS_MALGO eval $FIXTURE" \
  -n "Lean (eval)" "$LEAN_MALGO eval $FIXTURE"

echo
echo "=== compile + run (Zig backend, release-fast): naive fib(15), $FIXTURE ==="
HS_BIN="$WORK/hs-benchfib"
LEAN_BIN="$WORK/lean-benchfib"
"$HS_MALGO" compile "$FIXTURE" -o "$HS_BIN" --opt release-fast
"$LEAN_MALGO" compile "$FIXTURE" -o "$LEAN_BIN" --opt release-fast
hyperfine \
  --warmup 1 \
  --export-markdown "$WORK/compiled.md" \
  -n "Haskell-compiled" "$HS_BIN" \
  -n "Lean-compiled" "$LEAN_BIN"

{
  echo "# Lean vs. Haskell \`malgo\` runtime benchmark"
  echo
  echo "Generated by \`bash bench/lean-vs-haskell.sh\` on $(date -u +%Y-%m-%d) ($(uname -s) $(uname -m))."
  echo "Fixture: \`$FIXTURE\` (naive recursive fib(15), un-memoized — a CPU-bound"
  echo "workload; \`examples/malgo/Fib.mlg\` only computes fib(5), too small to"
  echo "produce a stable wall-clock difference). \`n = 15\` (not larger) because"
  echo "fib(18)/fib(20) reproducibly SIGSEGV when compiled via the Zig backend,"
  echo "identically on both implementations — a pre-existing bug, not fixed here."
  echo
  echo "## \`malgo eval\` (small-step interpreter)"
  echo
  cat "$WORK/eval.md"
  echo
  echo "## \`malgo compile --opt release-fast\` (Zig backend, compiled binary)"
  echo
  cat "$WORK/compiled.md"
} > "$OUT_MD"

echo
echo "Results written to $OUT_MD"
