name = "malgo"
version = "0.1.0"
defaultTargets = ["malgo", "malgo-lsp"]
testDriver = "test"

[[lean_lib]]
name = "Malgo"

[[lean_exe]]
name = "malgo"
root = "Main"

[[lean_exe]]
name = "malgo-lsp"
root = "LspMain"

[[lean_lib]]
name = "Test"
globs = ["Test.+"]

[[lean_exe]]
name = "test"
root = "Test.Main"
