name: SBOM upload

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  SBOM-upload:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Generate SBOM
      run: |
        curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b $RUNNER_TEMP
        $RUNNER_TEMP/syft scan dir:./ -o spdx-json=sbom.spdx.json
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: sbom
        path: sbom.spdx.json
    - name: SBOM upload
      uses: advanced-security/spdx-dependency-submission-action@169d22427d74f3faf93504e70b03eede8dab272a # v0.2.0
